name: Fork
on:
  workflow_dispatch:

#  schedule:
#    - cron: 0 8 */5 * *

jobs: 
  build:
    runs-on: Ubuntu-20.04
    name: fork仓库
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: fork
      uses: TobKed/github-forks-sync-action@master
      with:
        github_token: ${{ secrets.REPO_TOKEN }}
        upstream_repository: AutoBuild-Actions-BETA
        upstream_branch: master
        target_repository: 281677160/AutoBuild-BETA
        target_branch: main
        force: true
        tags: false
