
name: 重新Fork仓库
on:
  workflow_dispatch:

#  schedule:
#    - cron: 0 8 */5 * *

jobs: 
  build:
    runs-on: Ubuntu-20.04
    name: fork仓库
    steps:
    - name: fork
      uses: danshui-git/github-forks-sync-action@main
      with:
        github_token: ${{ secrets.REPO_TOKEN }}
        upstream_repository: lee29/build-actions
        upstream_branch: main
        target_repository: 281677160/amlogic-s9xxx-openwrt
        target_branch: main
        force: true
        tags: false
