name: fork仓库
on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      REPO_URL:
        description: '上游源码仓库(账号/仓库),比如：coolsnowwolf/lede'
        required: true
        default: ''
      REPO_BRANCH:
        description: '上游源码仓库的分支,比如：master 或 main 之类'
        required: true
        default: ''
      COMMIT_HASH:
        description: '回退上游仓库哈希值,比如(60824ec),不需回退则千万别填写'
        required: false
        default: ''
      MY_REPO_URL:
        description: '要替换仓库(账号/仓库),比如：281677160/actions-openwrt'
        required: true
        default: ''
      MY_REPO_BRANCH:
        description: '要替换仓库的分支,比如：master 或 main 之类'
        required: true
        default: ''

jobs: 
  build:
    runs-on: Ubuntu-22.04
    name: fork仓库
    
    steps:
    - name: 准备完毕
      uses: actions/checkout@v4

    - name: 密匙检测（密匙为空则退出）
      run: |
        cd ${GITHUB_WORKSPACE}
        if [[ -n "${{ secrets.REPO_TOKEN }}" ]]; then
          curl -s -H "Authorization: Bearer ${{ secrets.REPO_TOKEN }}" \
          https://api.github.com/repos/281677160/common/releases/tag/API > mishi
          if [[ `grep -c "Bad credentials" mishi` -ge '1' ]]; then
            echo "您的密匙不正确或已过期，请按教程设置好密匙再来"
            echo "REPO_TOKEN密匙制作教程：https://git.io/jm.md"
            exit 1
          fi
        elif [[ -z "${{ secrets.REPO_TOKEN }}" ]]; then
          echo "您没有设置仓库密匙，请按教程设置好密匙再来"
          echo "REPO_TOKEN密匙制作教程：https://git.io/jm.md"
          exit 1
        fi
    
    - name: 整理环境
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo -E apt-get -qq update
        sudo -E apt-get -qq install git git-core wget curl grep
        sudo timedatectl set-timezone "Asia/Shanghai"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"

    - name: 拉取上游仓库和清理要替换的仓库
      run: |
        cd $GITHUB_WORKSPACE
        git clone -b ${{ inputs.REPO_BRANCH }} --single-branch https://github.com/${{ inputs.REPO_URL }} upstream
        if [[ -n "${{ inputs.COMMIT_HASH }}" ]]; then
          cd upstream
          git reset --hard ${{ inputs.COMMIT_HASH }}
          cd ../
        fi
        git clone -b ${{ inputs.MY_REPO_BRANCH }} https://user:${{ secrets.REPO_TOKEN }}@github.com/${{ inputs.MY_REPO_URL }}.git Warehouse
        cd Warehouse
        rm -Rf *
        git rm --cache *

    - name: 替换仓库
      continue-on-error: true
      run: |
        cd $GITHUB_WORKSPACE
        cp -Rf upstream/* Warehouse
        sudo chmod -R +x Warehouse
        cd Warehouse
        git add .
        git commit -m "$(date +%Y年%m月%d号-%H点%M分)"
        git push --quiet "https://${{ secrets.REPO_TOKEN }}@github.com/${{ inputs.MY_REPO_URL }}" HEAD:${{ inputs.MY_REPO_BRANCH }}
