
name: 重新Fork仓库
on:
  workflow_dispatch:

#  schedule:
#    - cron: 0 8 */5 * *

jobs: 
  build:
    runs-on: Ubuntu-20.04
    name: fork仓库
    steps:
    - name: fork
      uses: danshui-git/github-forks-sync-action@main
      with:
        github_token: ${{ secrets.REPO_TOKEN }}
        upstream_repository: jerrykuku/luci-theme-argon
        upstream_branch: cb52e4d07f07b22241ac4a32fc18420770dfb4d3
        target_repository: 281677160/luci-theme-argon
        target_branch: main
        force: true
        tags: false
